module.exports = {
  defaultCharacterShape: {
    general: {
      name: '',
      class: '',
      race: '',
      align: '',
      deity: '',
      size: '',
      space: '',
      reach: '',
    },
    physical: {
      gender: '',
      height: '',
      weight: '',
      age: '',
      hair: '',
      eyes: '',
      skin: '',
      misc: '',
    },
    points: {
      hp: '',
      gp: '',
      level: '',
      xp: '',
      notes: '',
    },
    abilities: {
      str: '',
      dex: '',
      con: '',
      int: '',
      wis: '',
      cha: '',
    },
    attack: {
      melee: '',
      range: '',
      bab: '',
      cmb: '',
      conc: '',
      init: '',
    },
    defense: {
      ac: '',
      touch: '',
      cmd: '',
      fort: '',
      ref: '',
      will: '',
    },
    equipment: {
      'weapon 1': '',
      'weapon 2': '',
      'armor 1': '',
      'armor 2': '',
      'misc 1': '',
      'misc 2': '',
    },
  },
}
