module.exports = {
  defaultCharacterShape: {
    general: {
      name: '',
      class: '',
      race: '',
      align: '',
      deity: '',
      size: '',
      space: '',
      reach: '',
    },
    physical: {
      gender: '',
      height: '',
      weight: '',
      age: '',
      hair: '',
      eyes: '',
      skin: '',
      misc: '',
    },
    points: {
      hp: '',
      gp: '',
      level: '',
      xp: '',
      notes: '',
    },
    abilities: {
      str: '',
      dex: '',
      con: '',
      int: '',
      wis: '',
      cha: '',
    },
    attack: {
      melee: '',
      range: '',
      bab: '',
      cmb: '',
      conc: '',
      init: '',
    },
    defense: {
      ac: '',
      touch: '',
      cmd: '',
      fort: '',
      ref: '',
      will: '',
    },
    equipment: {
      'weapon 1': '',
      'weapon 2': '',
      'armor 1': '',
      'armor 2': '',
      'misc 1': '',
      'misc 2': '',
    },
  },
  heimdall: {
    general: {
      name: 'Heimdall',
      class: 'Paladin',
      race: 'Human',
      align: 'Lawful Good',
      deity: 'Sarenrae',
      size: 'Medium',
      space: '5ft (1x1)',
      reach: '5ft (1)',
    },
    physical: {
      gender: 'Male',
      height: '6ft 10in',
      weight: '260lbs',
      age: '27',
      hair: 'Brown',
      eyes: 'Brown',
      skin: 'Black',
      misc: '',
    },
    points: {
      hp: '',
      gp: '',
      level: '',
      xp: '',
      notes: '',
    },
    abilities: {
      str: '',
      dex: '',
      con: '',
      int: '',
      wis: '',
      cha: '',
    },
    attack: {
      melee: '',
      range: '',
      bab: '',
      cmb: '',
      conc: '',
      init: '',
    },
    defense: {
      ac: '',
      touch: '',
      cmd: '',
      fort: '',
      ref: '',
      will: '',
    },
    equipment: {
      'weapon 1': '',
      'weapon 2': '',
      'armor 1': '',
      'armor 2': '',
      'misc 1': '',
      'misc 2': '',
    },
  },
};
